added cicd 2

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -85,16 +85,16 @@ jobs:
         run: |
           docker pull ${{ secrets.AWS_ECR_LOGIN_URI }}/${{ secrets.ECR_REPOSITORY_NAME }}:latest
          
-      - name: Stop and remove container if running
-        run: |
-          echo "Checking if container cnncls exists..."
-          docker ps -q --filter "name=cnncls" | grep -q . && echo "Container cnncls found" || echo "Container cnncls not found"
+      # - name: Stop and remove container if running
+      #   run: |
+      #     echo "Checking if container cnncls exists..."
+      #     docker ps -q --filter "name=cnncls" | grep -q . && echo "Container cnncls found" || echo "Container cnncls not found"
     
-          echo "Stopping container cnncls..."
-          docker stop cnncls
+      #     echo "Stopping container cnncls..."
+      #     docker stop cnncls
     
-          echo "Removing container cnncls..."
-          docker rm -fv cnncls
+      #     echo "Removing container cnncls..."
+      #     docker rm -fv cnncls
 
       - name: Run Docker Image to serve users
         run: |
